theme: minima  # Ersetze 'minima' durch das gewünschte Theme
minima:
  skin: classic
  favicon: "https://mexelrobi.github.io/favicon.ico"
  navigation:
    - title: "Home"
      url: "/"
    - title: "Apps"
      url: "/apps/"
